### ISSUE TITLE
error in your code 

### ISSUE THREAD

**Issue by AhmedNassar5198** [U7P4L-IN/FB-BRUTE#7]
python FB2.py
  File "/home/kali/RedTeam/tools/FB-BRUTE/FB2.py", line 34
    print "\nTrying Passwords from list ..."
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

**Comment by U7P4L-IN** [comment]
Input ur error ss
